### ISSUE TITLE
PLAYLIST.TXT par ordre alphabétiques

### ISSUE THREAD

**Issue by music59940** [MajicDesigns/MD_MIDIFile#22]
Bonjour

Comment je peut faire pour que créer PLAYLIST.TXT par ordre alphabétique

merci pour votre soutien

**Comment by MajicDesigns** [comment]
The solution entirely depends on how many files you have to sort and the memory you have available in the microcontroller.

One option is to store all the files names that are found in an array, sort them using the built-in qsort() or your own algorithm and then write them in order to the file.

If you don't have enough memory then you will need to sort the records in the file (more complex algorithm). You need to search for "sort file lines algorithm" to get ideas.
